### ISSUE TITLE
Переменные в путях к файлам

### ISSUE THREAD

**Issue by pokidovea** [pokidovea/mimicro#25]
Нужна возможность передавать переменную из урла в путь к файлу:
```yaml
url: /some/{var}
GET: 
    file: "file:///path/to/file_{{.var}}.json"
```
Что должно означать: при запросе 
```
/some/12
```
Вернуть файл
```
/path/to/file_12.json
```

Это правило должно работать исключительно с file, но не с template, т.к. путь к темплейту должен быть известен на момент старта приложения.
